# API LLM Rate Limit Configuration

# OpenAI Models
openai:
  gpt-4o-mini-2024-07-18:
    usage_tier=0: # free tier
      RPM: 3
      TPM: 40000
    usage_tier=1:
      RPM: 500
      TPM: 200000
    usage_tier=2:
      RPM: 5000
      TPM: 2000000
    usage_tier=3:
      RPM: 5000
      TPM: 4000000
  gpt-4o-2024-11-20:
    usage_tier=1:
      RPM: 500
      TPM: 30000
    usage_tier=2:
      RPM: 5000
      TPM: 450000
    usage_tier=3:
      RPM: 5000
      TPM: 800000

# Gemini Models
gemini:
  gemini-1.5-flash-002:
    usage_tier=0: # free tier
      RPM: 15
      TPM: 1000000
    usage_tier=1:
      RPM: 2000
      TPM: 4000000
  gemini-1.5-pro-002:
    usage_tier=0: # free tier
      RPM: 2
      TPM: 32000000
    usage_tier=1:
      RPM: 1000
      TPM: 4000000
  gemini-1.5-flash-8b-001:
    usage_tier=0: # free tier
      RPM: 15
      TPM: 1000000
    usage_tier=1:
      RPM: 4000
      TPM: 4000000
  gemini-2.0-flash-exp:
    usage_tier=0: # free tier
      RPM: 10
      TPM: 4000000

# Anthropic Models
anthropic:
  claude-3-5-sonnet-20241022:
    usage_tier=1:
      RPM: 50
      TPM: 40000
    usage_tier=2:
      RPM: 1000
      TPM: 80000
  claude-3-5-haiku-20241022:
    usage_tier=1:
      RPM: 50
      TPM: 50000
    usage_tier=2:
      RPM: 1000
      TPM: 100000
