female(anastasia)
female(angelina)
female(charlotte)
female(clara)
female(elena)
female(helga)
female(lena)
female(lisa)
female(mia)
female(natalie)
female(nora)
female(sarah)
female(vanessa)

male(elias)
male(fabian)
male(felix)
male(gabriel)
male(jan)
male(lorenz)
male(maximilian)
male(michael)
male(oskar)
male(patrick)
male(simon)
male(thomas)
male(vincent)

parent(anastasia, sarah)
parent(angelina, natalie)
parent(charlotte, clara)
parent(charlotte, fabian)
parent(charlotte, lisa)
parent(charlotte, thomas)
parent(elena, michael)
parent(elena, nora)
parent(elias, michael)
parent(elias, nora)
parent(helga, felix)
parent(helga, gabriel)
parent(jan, elias)
parent(lena, elias)
parent(lisa, simon)
parent(lorenz, natalie)
parent(maximilian, clara)
parent(maximilian, fabian)
parent(maximilian, lisa)
parent(maximilian, thomas)
parent(mia, anastasia)
parent(michael, simon)
parent(oskar, elena)
parent(patrick, sarah)
parent(sarah, lorenz)
parent(simon, felix)
parent(simon, gabriel)
parent(thomas, lorenz)
parent(vanessa, elena)
parent(vincent, anastasia)