ppl_2_ppl = {
    "brother": "The brother of <subject> is",
    "sister": "The sister of <subject> is",
    "sibling": "<subject>'s siblings are",
    "father": "The father of <subject> is",
    "mother": "The mother of <subject> is",
    "spouse": "<subject>'s spouse is",
    "child": "The child of <subject> is",
    "stepfather": "The stepfather of <subject> is",
    "stepmother": "The stepmother of <subject> is",
    "follows": "<subject> follows",
    "number of children": "The number of children <subject> has is",
    "uncle": "The uncle of <subject> is",
    "aunt": "The aunt of <subject> is",
}
ppl_2_socialconstructs = {
    "country": "The country which <subject> is associated with is",
    "place of birth": "The city in which <subject> was born is",
    "place of death": "The city in which <subject> died is",
    "country of citizenship": "The country of citizenship of <subject> is",
    "position held": "The position that has been held by <subject> is",
    "alma mater": "<subject> has been educated at",
    "occupation": "The occupation of <subject> is",
    "employer": "<subject>'s employer is",
    "league": "The league in which <subject> plays is",
    "place of burial": "The country in which <subject> is buried is",
    # 'ethnic group': 'The ethnic group which <subject> is associated with is',
    # 'religion': 'The religion which <subject> is associated with is',
}
ppl_2_objs = {
    # 'sex or gender': "<subject>'s gender is",
    # 'sexual orientation': "<subject>'s sexual orientation is",
    "native language": "The mother tongue of <subject> is",
    "field of work": "<subject> has been working in the field of",
    "eye color": "The eye color of <subject> is",
    "award received": "<subject> has won the award of",
    "date of birth": "The date in which <subject> was born in is",
}
places = {
    "head of government": "The head of government of <subject> is",
    "continent": "The continent which <subject> is part of is",
    "head of state": "The head of state of <subject> is",
    "capital": "The capital of <subject> is",
    "currency": "The currency in <subject> is",
    "official language": "The official language of <subject> is",
    "anthem": "The anthem of <subject> is",
    "cast member": "<subject>'s cast members are",
    "capital of": "<subject> is the capital of",
}
things = {
    # 'author': 'The author of <subject> is',
    # 'member of sports team': '<subject> has been a member of a sports team. This team is',
    # 'director': 'The director of <subject> is',
    # 'screenwriter': 'The screenwriter of <subject> is',
    # 'architect': 'The architect of <subject> is',
    # 'composer': 'The composer of <subject> is',
    # 'editor': 'The editor of <subject> is',
    # 'founder': 'The founder of <subject> is',
    "author": "<subject> is the author of",
    "member of sports team": "<subject> has been a member of a sports team. This team is",
    "director": "<subject> is the director of",
    "screenwriter": "<subject> is the screenwriter of",
    "architect": "<subject> is the architect of",
    "composer": "<subject> is the composer of",
    "editor": "<subject> is the editor of",
    "founder": "<subject> is the founder of",
}
